import type {
  ExternalAuthorization,
  ExternalPost,
  ExternalTokens,
} from "../external-post";
import type { SocialProviderConfig, SocialProviderId } from "../social-sync.config";

/**
 * What every platform integration must implement.
 *
 * ## The point of the interface
 *
 * Without it, the controller, the sync job and the settings screen would each need to know
 * which platform they are dealing with, and the platform-specific branches would spread
 * until "add a platform" meant editing a dozen files. With it, adding a platform is one new
 * file plus one registration, and nothing else changes.
 *
 * ## Why `getRecentPosts` takes a limit
 *
 * The member chooses 1–3 posts, and the limit is enforced on the way IN as well as out.
 * Requesting a fixed page and discarding the rest wastes quota — YouTube's Data API bills
 * in units, and X's free tier is a few hundred reads a month — so the adapters are told how
 * many are actually wanted.
 *
 * ## Why `refreshToken` returns tokens rather than mutating
 *
 * An adapter has no database access by design: it is the only part of the system that talks
 * to a third party, and keeping it pure makes it testable without a database and impossible
 * for a provider bug to write to a table. Persisting the refreshed tokens is the caller's
 * job.
 */
export interface SocialProviderAdapter {
  readonly provider: SocialProviderId;

  /**
   * The URL to send the member's browser to.
   *
   * `state` is generated by the caller and must travel verbatim; `codeChallenge` is the
   * PKCE challenge for providers that require it, and is ignored by those that do not.
   */
  getAuthorizationUrl(input: { config: SocialProviderConfig; state: string; codeChallenge: string | null; redirectUri: string }): string;

  /**
   * Exchanges the authorization code for tokens, and reads the account they belong to.
   *
   * One method rather than `exchangeCode` + `getAccount` because the second call needs the
   * access token the first produced, and a caller that forgets to make it would store a
   * connection with no identity attached.
   */
  handleCallback(input: {
    config: SocialProviderConfig;
    code: string;
    codeVerifier: string | null;
    redirectUri: string;
  }): Promise<ExternalAuthorization>;

  /** Renews an access token. Throws `SOCIAL_TOKEN_REFRESH_FAILED` when it cannot. */
  refreshToken(input: { config: SocialProviderConfig; refreshToken: string }): Promise<ExternalTokens>;

  /** The account behind an access token. Used to re-read identity after a refresh. */
  getAccount(input: { config: SocialProviderConfig; accessToken: string }): Promise<ExternalAuthorization["account"]>;

  /**
   * The member's most recent posts, newest first, at most `limit`.
   *
   * Must return at most `limit` items and must be safe to call repeatedly: the caller
   * deduplicates by `externalPostId`, so a repeat returns the same ids rather than new rows.
   */
  getRecentPosts(input: {
    config: SocialProviderConfig;
    accessToken: string;
    /** The provider's own account id, when the API needs it to scope the query. */
    providerUserId: string;
    limit: number;
  }): Promise<ExternalPost[]>;

  /**
   * Tells the provider to drop the grant.
   *
   * Best-effort by contract: a provider that has already revoked, or that has no revocation
   * endpoint, must not prevent the local unbind. The caller treats a throw here as a warning.
   */
  revoke(input: { config: SocialProviderConfig; accessToken: string }): Promise<void>;

  /**
   * Whether this adapter can serve `getRecentPosts` at all.
   *
   * `false` for the platforms that need a developer-programme approval this deployment does
   * not have. Kept on the interface rather than modelled as a missing adapter so the
   * settings screen can list every platform the product advertises, with an honest reason
   * for the ones that cannot be connected — which is what the brief asks for.
   */
  readonly canReadPosts: boolean;
}
