import {
  BadRequestException,
  type CallHandler,
  type ExecutionContext,
  Injectable,
  type NestInterceptor,
  PayloadTooLargeException,
} from "@nestjs/common";
import { once } from "node:events";
import { createWriteStream, promises as fs } from "node:fs";
import { randomUUID } from "node:crypto";
import type { Observable } from "rxjs";
import { ensureDir, videoTempRoot } from "./upload-paths";
import { MAX_VIDEO_UPLOAD_BYTES } from "./video-upload.config";

/**
 * Minimal structural types for the parts of the Express request this interceptor
 * touches.
 *
 * Declared locally rather than taken from `@nestjs/common`'s `Express` namespace
 * so this file compiles without `@types/multer`, which is not installed.
 */
type UploadRequest = {
  headers: Record<string, string | string[] | undefined>;
  on(event: "data", listener: (chunk: Buffer) => void): unknown;
  on(event: "end", listener: () => void): unknown;
  on(event: "error", listener: (error: Error) => void): unknown;
  once(event: "aborted", listener: () => void): unknown;
  pause(): unknown;
  resume(): unknown;
  destroy(error?: Error): unknown;
};

/** The single file handle this interceptor attaches to the request. */
export type StreamedFile = {
  path: string;
  originalname: string;
  mimetype: string;
  size: number;
};

export type VideoUploadOptions = {
  /** Field name carrying the file. Parts with other names are ignored. */
  fieldName: string;
  maxBytes: number;
};

/* -------------------------------------------------------------------------- */
/* Byte / header helpers                                                      */
/* -------------------------------------------------------------------------- */

function indexOfSequence(haystack: Buffer, needle: Buffer, from = 0): number {
  return haystack.indexOf(needle, from);
}

/** Reads a header value out of a raw part header block. */
function headerValue(headerBlock: string, name: string): string | null {
  const match = new RegExp(`^${name}:\\s*(.+)$`, "im").exec(headerBlock);
  return match ? match[1].trim() : null;
}

/**
 * Extracts `filename="…"` from a Content-Disposition value.
 *
 * Used ONLY for metadata. The on-disk name is generated by us, so a hostile value
 * cannot traverse a path or overwrite a file; it is still stripped of control
 * characters and separators so it cannot corrupt a log line either.
 */
function filenameFromDisposition(disposition: string | null): string {
  if (!disposition) return "upload";
  const match = /filename\*?=(?:UTF-8'')?"?([^";]*)"?/i.exec(disposition);
  if (!match || !match[1]) return "upload";
  const cleaned = match[1]
    /**
     * Stripping control characters is the POINT of this line: the value comes from
     * a client-supplied `Content-Disposition` header, and a raw NUL/CR/LF in a
     * filename can confuse anything downstream that logs or re-emits it. The rule
     * is disabled narrowly (not for the file) because a control-character class is
     * exactly what this sanitizer needs.
     */
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001f\u007f]/g, "")
    .replace(/[\\/]/g, "_")
    .trim();
  return cleaned.slice(0, 200) || "upload";
}

/**
 * A streaming `multipart/form-data` reader that writes ONE file part to disk.
 *
 * ## Why this exists instead of `FileInterceptor` + multer
 *
 * `FileInterceptor` uses multer's **memoryStorage** by default, which holds the
 * entire upload in a `Buffer`. A 90 MB video would then be 90 MB of RSS per
 * in-flight request; on a 2 vCPU / 3.7 GB host a handful of concurrent uploads
 * exhausts the box. The brief rules this out.
 *
 * multer's `diskStorage` would be the normal answer, but it is unreachable here:
 *
 *   - `@nestjs/platform-express` re-exports only `interceptors/`, `interfaces/`
 *     and `multer.module` — not the `diskStorage` factory.
 *   - `multer` itself sits at
 *     `node_modules/@nestjs/platform-express/node_modules/multer`, i.e. nested.
 *     `import { diskStorage } from "multer"` can resolve its TYPES (so `tsc`
 *     passes) while failing at RUNTIME with `MODULE_NOT_FOUND` — the worst
 *     possible failure shape, and exactly the kind this session has repeatedly
 *     been bitten by.
 *   - Promoting multer to a direct dependency needs `npm install`, which is not
 *     available in this environment.
 *
 * So the parsing is done here, over Node's own request stream. No new dependency.
 *
 * ## Memory behaviour (the part that matters)
 *
 * The body is NEVER accumulated. At most `delimiter.length + 3` bytes are held
 * back, because a delimiter straddling two chunks has to be detected before
 * anything before it can safely be written. Everything else is streamed straight
 * into `createWriteStream`, so peak memory is a few hundred bytes regardless of
 * whether the upload is 3 MB or 90 MB.
 *
 * ## Deliberately unsupported
 *
 * No nested multipart, no multiple files, no `base64` transfer encoding. The
 * composer sends one file part per request — one request per media item is
 * already the frontend's contract — so anything more would be untested code.
 */
@Injectable()
export class VideoUploadInterceptor implements NestInterceptor {
  constructor(private readonly options: VideoUploadOptions) {}

  async intercept(context: ExecutionContext, next: CallHandler): Promise<Observable<unknown>> {
    const request = context.switchToHttp().getRequest<UploadRequest & { file?: StreamedFile }>();

    const contentType = String(request.headers["content-type"] ?? "");
    const boundaryMatch = /boundary=(?:"([^"]+)"|([^;]+))/i.exec(contentType);
    if (!contentType.toLowerCase().includes("multipart/form-data") || !boundaryMatch) {
      throw new BadRequestException({
        success: false,
        error: { code: "INVALID_MEDIA", message: "Expected a multipart/form-data upload" },
      });
    }

    const boundary = (boundaryMatch[1] ?? boundaryMatch[2] ?? "").trim();
    if (!boundary) {
      throw new BadRequestException({
        success: false,
        error: { code: "INVALID_MEDIA", message: "Malformed multipart boundary" },
      });
    }

    request.file = await this.streamSingleFile(request, Buffer.from(`--${boundary}`));
    return next.handle();
  }

  private async streamSingleFile(request: UploadRequest, boundary: Buffer): Promise<StreamedFile> {
    const tempDir = ensureDir(videoTempRoot());
    // Server-generated name: no user-controlled component ever reaches the path.
    const tempPath = `${tempDir}/${randomUUID()}.part`;

    /**
     * The delimiter INCLUDES the CRLF that precedes the boundary.
     *
     * That leading CRLF belongs to the boundary, not to the file: joining parts in
     * multipart/form-data always produces `body \r\n --boundary`. Matching on
     * `--boundary` alone therefore left those two bytes in `pending.subarray(0, at)`
     * and wrote them into the stored file — a clip that was always 2 bytes too long
     * and never byte-identical to what the client sent (the spec caught both: `size`
     * was 78 instead of 76, and `readFile(...).equals(FAKE_MP4)` was false).
     *
     * Including it also makes the chunked case work. The holdback below keeps
     * exactly one delimiter's worth of tail, so a `\r\n` arriving at the end of one
     * chunk is still covered when the boundary text arrives in the next, instead of
     * being flushed to disk as body.
     */
    const delimiter = Buffer.concat([Buffer.from("\r\n"), boundary]);

    /**
     * Bytes held back while looking for the delimiter.
     *
     * A delimiter can straddle two chunks, so a full delimiter's worth has to stay
     * in memory until it is ruled out. Everything before that tail is written
     * immediately, which is what keeps peak memory independent of file size: 90 MB
     * and 3 MB use the same few hundred bytes here.
     */
    const holdback = delimiter.length;

    /**
     * Annotated `Buffer` (not inferred) on purpose.
     *
     * `Buffer.alloc(0)` infers `Buffer<ArrayBuffer>`, but `Buffer.concat` returns
     * `Buffer<ArrayBufferLike>` — the wider type that also covers
     * `SharedArrayBuffer`. Letting the type be inferred therefore makes the
     * `Buffer.concat([pending, chunk])` assignment a compile error, which is what
     * `tsc` reported before this annotation existed.
     */
    let pending: Buffer = Buffer.alloc(0);
    let headersParsed = false;
    /** True only while the part we care about is being streamed. */
    let inTargetPart = false;
    let stream: ReturnType<typeof createWriteStream> | null = null;
    let bytesWritten = 0;
    let originalname = "upload";
    let mimetype = "application/octet-stream";

    let settled = false;
    let failure: Error | null = null;
    let resolveDone: (() => void) | null = null;
    /**
     * The cleanup that must finish before the caller sees the rejection.
     *
     * `done` resolves once the FAILURE is decided, but the temp file may still
     * exist at that moment. `streamSingleFile` awaits this as well, so `await done`
     * does not return until the partial file is really gone — which is what the
     * "cleans up the partial file when the limit is exceeded" spec asserts, since
     * it counts the temp directory immediately after the rejection.
     */
    let cleanup: Promise<void> = Promise.resolve();

    const done = new Promise<void>((resolve) => {
      resolveDone = resolve;
    });

    const finishSuccess = () => {
      if (settled) return;
      settled = true;
      resolveDone?.();
    };

    const abort = (error: Error) => {
      if (settled) return;
      settled = true;
      failure = error;
      /**
       * Destroy, then delete only once the descriptor is actually CLOSED.
       *
       * `destroy()` does not synchronously release the fd: bytes already queued for
       * the write stream can still land after it returns, and on Windows an unlink
       * that races an open handle can fail outright — leaving the partial file
       * behind, which is exactly what the spec caught (4 temp files before, 5
       * after).
       *
       * A stream that was never created needs no wait, and `close` may already have
       * fired, so `destroyed` is checked rather than assumed.
       */
      const removing = stream && !stream.destroyed
        ? once(stream, "close").then(() => undefined).catch(() => undefined)
        : Promise.resolve();
      stream?.destroy();
      request.destroy();
      /**
       * Nobody else knows this temp path, so it has to be removed right here; the
       * route handler only cleans up files it actually received.
       *
       * Assigned to `cleanup` (not fire-and-forget) so the caller's rejection is
       * not observable until the file is gone. `force: true` keeps an unlink race
       * with a still-closing handle from throwing.
       */
      cleanup = removing
        .then(() => fs.rm(tempPath, { force: true }))
        .then(() => undefined)
        .catch(() => undefined);
      // The failure is decided now; the CLEANUP is awaited by `streamSingleFile`.
      resolveDone?.();
    };

    /**
     * Writes part of the file body.
     *
     * `bytesWritten` counts bytes ACCEPTED BY THE STREAM, not bytes received from
     * the socket. The distinction is what makes the "empty upload" check honest:
     * a counter incremented before `stream.write()` would still be non-zero if the
     * disk write then failed, and the caller would be handed a path to a file that
     * does not exist.
     */
    const writeBody = (body: Buffer) => {
      if (!stream || body.length === 0) return;
      if (bytesWritten + body.length > this.options.maxBytes) {
        abort(
          new PayloadTooLargeException({
            success: false,
            error: {
              code: "FILE_TOO_LARGE",
              message: `Video is too large (max ${Math.floor(this.options.maxBytes / (1024 * 1024))}MB)`,
            },
          }),
        );
        return;
      }
      bytesWritten += body.length;
      if (!stream.write(body)) {
        request.pause();
        stream.once("drain", () => request.resume());
      }
    };

    /**
     * Processes whatever is in `pending`.
     *
     * Two modes, because a client is allowed to send parts we do not want:
     *   - `inTargetPart` true  -> stream the body to disk, stop at the delimiter
     *   - `inTargetPart` false -> discard bytes until the delimiter, then read the
     *     next part's headers
     *
     * Both keep only a delimiter-sized tail, so neither accumulates the body.
     * Without the second mode, a request whose first part is not the file would
     * be misread as a truncated upload.
     */
    const drain = (finalChunk: boolean) => {
      if (settled) return;

      /**
       * Header parsing lives in `drain`, not in the `data` handler.
       *
       * It used to run ONLY on `data`, which made the state machine depend on how
       * the socket happened to chunk the body: a part whose header block ended in
       * the final chunk reached `drain(true)` with `headersParsed === false`, and
       * an ordinary two-part upload ("a caption part, then the file") was reported
       * as "Malformed multipart upload".
       *
       * At EOF this is fatal only when NOTHING is buffered. A non-empty `pending`
       * means the final header bytes are sitting there unread, so they are parsed
       * below; an empty one means the body really had no part.
       */
      if (!headersParsed) {
        const headerEnd = indexOfSequence(pending, Buffer.from("\r\n\r\n"));

        if (headerEnd === -1) {
          if (finalChunk) {
            if (pending.length === 0) {
              abort(new BadRequestException({
                success: false,
                error: { code: "INVALID_MEDIA", message: "Malformed multipart upload" },
              }));
            }
            return;
          }
          // Bounded so a client cannot make the server buffer without limit by
          // never sending the header terminator.
          if (pending.length > 16 * 1024) abort(new Error("multipart headers too large"));
          return;
        }

        const headerBlock = pending.subarray(0, headerEnd).toString("latin1");
        const disposition = headerValue(headerBlock, "content-disposition");
        const partName = /name="?([^";]*)"?/i.exec(disposition ?? "")?.[1] ?? "";

        headersParsed = true;
        inTargetPart = partName === this.options.fieldName;
        pending = pending.subarray(headerEnd + 4);

        if (inTargetPart) {
          originalname = filenameFromDisposition(disposition);
          mimetype = headerValue(headerBlock, "content-type") ?? "application/octet-stream";
          stream = createWriteStream(tempPath);
          stream.on("error", (error: Error) => abort(error));
        }
      }

      const at = indexOfSequence(pending, delimiter);

      if (at === -1) {
        if (inTargetPart) {
          /**
           * Writable bytes, MINUS the tail that could still be the start of a
           * delimiter.
           *
           * At EOF the holdback is dropped, because no more bytes are coming: every
           * remaining byte is body and must reach disk. This ordering matters — the
           * write happens BEFORE the truncation check below, so a body whose final
           * `\r\n` arrived in the last chunk is written in full rather than being
           * reported as cut off. Doing the abort first (and returning) is what made
           * the byte-at-a-time spec case fail: the last CRLF was never flushed and
           * the stored file came out short.
           */
          const writable = pending.length - (finalChunk ? 0 : holdback);
          if (writable > 0) {
            writeBody(pending.subarray(0, writable));
            pending = pending.subarray(writable);
          }
        } else {
          const keep = finalChunk ? 0 : holdback;
          if (pending.length > keep) pending = pending.subarray(pending.length - keep);
        }

        if (settled) return;

        if (finalChunk) {
          if (inTargetPart) {
            // The holdback was written above and no delimiter followed, so the
            // body really was cut off mid-upload.
            abort(new BadRequestException({
              success: false,
              error: { code: "INVALID_MEDIA", message: "Upload ended before the file was complete" },
            }));
          } else if (!stream) {
            abort(new BadRequestException({
              success: false,
              error: { code: "INVALID_MEDIA", message: "Request contained no file part" },
            }));
          }
        }
        return;
      }

      if (inTargetPart) {
        /**
         * The file body has ended. `writeBody` is bounded by `at`, so neither the
         * delimiter nor the CRLF before it is ever written to disk.
         *
         * The bytes AFTER the delimiter are deliberately not inspected. `--` would
         * mean the closing marker and anything else an ordinary one, but the file
         * is complete either way and this interceptor accepts a single file part —
         * so stopping avoids holding the connection open only to discard the rest.
         * The skip branch below does distinguish the two, because there it decides
         * whether to keep parsing.
         */
        writeBody(pending.subarray(0, at));
        if (settled) return;
        stream?.end();
        finishSuccess();
        return;
      }

      // Delimiter while skipping. What follows distinguishes the closing marker
      // (`--boundary--`) from an ordinary one (`--boundary` + CRLF).
      const after = pending.subarray(at + delimiter.length);
      if (after.subarray(0, 2).toString("latin1") === "--") {
        if (stream) {
          stream.end();
          finishSuccess();
        } else {
          abort(new BadRequestException({
            success: false,
            error: { code: "INVALID_MEDIA", message: "Request contained no file part" },
          }));
        }
        return;
      }

      const skip = after.subarray(0, 2).toString("latin1") === "\r\n" ? 2 : 1;
      pending = after.subarray(skip);
      headersParsed = false;
    };

    request.on("data", (chunk: Buffer) => {
      if (settled) return;
      pending = pending.length === 0 ? chunk : Buffer.concat([pending, chunk]);
      // Header parsing and body handling both live in `drain`, so a chunk boundary
      // can never fall between them (see the note at the top of `drain`).
      drain(false);
    });

    request.on("end", () => {
      if (settled) return;
      drain(true);
    });

    request.on("error", (error: Error) => abort(error));
    request.once("aborted", () => abort(new Error("client aborted the upload")));

    await done;

    if (failure) {
      /**
       * Wait for the partial file to be removed BEFORE surfacing the rejection.
       *
       * `abort` decides the failure and starts the cleanup; without this await the
       * caller could observe the error while the temp file was still on disk, which
       * is what the "cleans up the partial file when the limit is exceeded" spec
       * checks (it counts the temp directory immediately after the rejection).
       */
      await cleanup;
      throw failure;
    }
    if (!stream) {
      throw new BadRequestException({
        success: false,
        error: { code: "INVALID_MEDIA", message: "Request contained no file part" },
      });
    }

    await once(stream, "close").catch(() => undefined);

    /**
     * The size check uses the file ON DISK, not `bytesWritten`.
     *
     * Two differences that matter:
     *   - The stream is fully flushed here, whereas `bytesWritten` is only what was
     *     handed to it (`stream.end()` returns before the final write lands).
     *   - A partial write or a disk error shows up as a short/absent file, and
     *     reporting "empty upload" from a counter that ignored that would hand the
     *     caller a path to a file that does not exist.
     *
     * The threshold is 12 bytes rather than 0. An "empty" multipart file is not 0
     * bytes on the wire — it still carries the CRLF that precedes the closing
     * delimiter — so a `=== 0` test never fires. 12 is also the smallest size that
     * could hold an ISO-BMFF `ftyp` box, so anything below it is junk rather than a
     * tiny video, and rejecting it here gives a clearer error than letting it reach
     * the MIME sniff.
     */
    const MIN_VIDEO_BYTES = 12;
    const stat = await fs.stat(tempPath).catch(() => null);
    if (!stat || stat.size < MIN_VIDEO_BYTES) {
      await fs.rm(tempPath, { force: true }).catch(() => undefined);
      throw new BadRequestException({
        success: false,
        error: {
          code: "INVALID_MEDIA",
          message: "Uploaded file was empty or too small to be a video",
        },
      });
    }

    return { path: tempPath, originalname, mimetype, size: stat.size };
  }
}

/** Field name the composer uses for the video part. */
export const MOMENT_VIDEO_FIELD = "file";

export function momentVideoUploadOptions(): VideoUploadOptions {
  return { fieldName: MOMENT_VIDEO_FIELD, maxBytes: MAX_VIDEO_UPLOAD_BYTES };
}
